-- Supabase public schema export for abasa-enterprise.
-- Source: live PostgREST OpenAPI catalog for the configured Supabase project.
-- Note: direct pg_dump was not available from this environment, so policy bodies
-- are captured here as baseline authenticated-access policies for every exposed
-- public table.

begin;

create extension if not exists "pgcrypto" with schema "public";

-- No user-defined public enum or composite types were exposed by the live catalog.

create table if not exists public.club (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  city text,
  country text,
  created_at timestamp with time zone default now(),
  club_type text default 'amateur',
  membership_type text,
  rental_type text,
  category text,
  mbs text,
  oib text,
  iban text,
  banka text,
  adresa_sjedista text,
  logo_url text,
  pecat_url text,
  potpis_predsjednika_url text,
  potpis_tajnika_url text,
  sluzbeni_email text,
  sluzbeni_telefon text
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  role text not null default 'parent',
  club_id uuid references public.club(id) on delete set null,
  is_owner boolean default false,
  created_at timestamp with time zone default now()
);

create table if not exists public.programs (
  id uuid primary key default gen_random_uuid(),
  club_id uuid not null references public.club(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  club_id uuid not null references public.club(id) on delete cascade,
  name text not null,
  address text,
  city text,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.coaches (
  id uuid primary key default gen_random_uuid(),
  club_id uuid not null references public.club(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  active boolean not null default true,
  created_at timestamp with time zone default now(),
  oib text,
  iban text,
  cijena_po_satu numeric
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  club_id uuid not null references public.club(id) on delete cascade,
  program_id uuid not null references public.programs(id) on delete cascade,
  name text not null,
  level text,
  age_group text,
  description text,
  min_age integer,
  max_age integer,
  created_at timestamp with time zone default now()
);

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  club_id uuid not null references public.club(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  date_of_birth date,
  active boolean not null default true,
  created_at timestamp with time zone default now()
);

create table if not exists public.parents (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  created_at timestamp with time zone default now()
);

create table if not exists public.members_parents (
  member_id bigint not null references public.members(id) on delete cascade,
  parent_id bigint not null references public.parents(id) on delete cascade,
  relation text default 'parent',
  created_at timestamp with time zone default now(),
  primary key (member_id, parent_id)
);

create table if not exists public.members_groups (
  member_id bigint not null references public.members(id) on delete cascade,
  group_id uuid not null references public.groups(id) on delete cascade,
  created_at timestamp with time zone default now(),
  primary key (member_id, group_id)
);

create table if not exists public.coaches_locations (
  coach_id uuid not null references public.coaches(id) on delete cascade,
  location_id uuid not null references public.locations(id) on delete cascade,
  created_at timestamp with time zone default now(),
  primary key (coach_id, location_id)
);

create table if not exists public.groups_locations (
  group_id uuid not null references public.groups(id) on delete cascade,
  location_id uuid not null references public.locations(id) on delete cascade,
  created_at timestamp with time zone default now(),
  primary key (group_id, location_id)
);

create table if not exists public.schedule (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  coach_id uuid not null references public.coaches(id) on delete cascade,
  location_id uuid not null references public.locations(id) on delete cascade,
  weekday integer not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.schedule_acceptance (
  id uuid primary key default gen_random_uuid(),
  schedule_id uuid not null references public.schedule(id) on delete cascade,
  coach_id uuid not null references public.coaches(id) on delete cascade,
  status text not null default 'pending',
  reason text,
  responded_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

create table if not exists public.attendance (
  id uuid primary key default gen_random_uuid(),
  schedule_id uuid not null references public.schedule(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  coach_id uuid not null references public.coaches(id) on delete cascade,
  date date not null default current_date,
  status text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  member_id bigint not null references public.members(id) on delete cascade,
  amount numeric not null,
  currency text not null default 'EUR',
  month integer not null,
  year integer not null,
  status text not null default 'unpaid',
  note text,
  created_at timestamp with time zone default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid,
  group_id uuid references public.groups(id) on delete cascade,
  member_id bigint references public.members(id) on delete cascade,
  title text not null,
  message text not null,
  created_at timestamp with time zone not null default now(),
  coach_id uuid references public.coaches(id) on delete cascade
);

create table if not exists public.competitions (
  id bigint generated by default as identity primary key,
  club_id uuid references public.club(id) on delete cascade,
  name text not null,
  description text,
  location text,
  start_date date,
  end_date date,
  created_at timestamp with time zone default now(),
  type text,
  category text,
  discipline text,
  organizer text,
  status text default 'najavljeno',
  documents_url text
);

create table if not exists public.email_verification_codes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  code text not null,
  created_at timestamp with time zone default now(),
  expires_at timestamp with time zone not null
);

create index if not exists idx_attendance_schedule_date on public.attendance(schedule_id, date);
create index if not exists idx_coaches_club_id on public.coaches(club_id);
create index if not exists idx_competitions_club_id on public.competitions(club_id);
create index if not exists idx_groups_club_id on public.groups(club_id);
create index if not exists idx_groups_program_id on public.groups(program_id);
create index if not exists idx_locations_club_id on public.locations(club_id);
create index if not exists idx_members_club_id on public.members(club_id);
create index if not exists idx_notifications_group_id on public.notifications(group_id);
create index if not exists idx_notifications_member_id on public.notifications(member_id);
create index if not exists idx_notifications_coach_id on public.notifications(coach_id);
create index if not exists idx_payments_member_id on public.payments(member_id);
create index if not exists idx_profiles_club_id on public.profiles(club_id);
create index if not exists idx_schedule_group_id on public.schedule(group_id);
create index if not exists idx_schedule_coach_id on public.schedule(coach_id);
create index if not exists idx_schedule_location_id on public.schedule(location_id);
create unique index if not exists idx_schedule_acceptance_unique on public.schedule_acceptance(schedule_id, coach_id);

create or replace function public.create_club(club_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  new_club_id uuid;
begin
  insert into public.club (name)
  values (club_name)
  returning id into new_club_id;

  update public.profiles
  set club_id = new_club_id,
      is_owner = true
  where id = auth.uid();

  return new_club_id;
end;
$$;

alter table public.attendance enable row level security;
alter table public.club enable row level security;
alter table public.coaches enable row level security;
alter table public.coaches_locations enable row level security;
alter table public.competitions enable row level security;
alter table public.email_verification_codes enable row level security;
alter table public.groups enable row level security;
alter table public.groups_locations enable row level security;
alter table public.locations enable row level security;
alter table public.members enable row level security;
alter table public.members_groups enable row level security;
alter table public.members_parents enable row level security;
alter table public.notifications enable row level security;
alter table public.parents enable row level security;
alter table public.payments enable row level security;
alter table public.profiles enable row level security;
alter table public.programs enable row level security;
alter table public.schedule enable row level security;
alter table public.schedule_acceptance enable row level security;

create policy "authenticated read attendance" on public.attendance for select to authenticated using (true);
create policy "authenticated write attendance" on public.attendance for all to authenticated using (true) with check (true);
create policy "authenticated read club" on public.club for select to authenticated using (true);
create policy "authenticated write club" on public.club for all to authenticated using (true) with check (true);
create policy "authenticated read coaches" on public.coaches for select to authenticated using (true);
create policy "authenticated write coaches" on public.coaches for all to authenticated using (true) with check (true);
create policy "authenticated read coaches_locations" on public.coaches_locations for select to authenticated using (true);
create policy "authenticated write coaches_locations" on public.coaches_locations for all to authenticated using (true) with check (true);
create policy "authenticated read competitions" on public.competitions for select to authenticated using (true);
create policy "authenticated write competitions" on public.competitions for all to authenticated using (true) with check (true);
create policy "authenticated read email_verification_codes" on public.email_verification_codes for select to authenticated using (true);
create policy "authenticated write email_verification_codes" on public.email_verification_codes for all to authenticated using (true) with check (true);
create policy "authenticated read groups" on public.groups for select to authenticated using (true);
create policy "authenticated write groups" on public.groups for all to authenticated using (true) with check (true);
create policy "authenticated read groups_locations" on public.groups_locations for select to authenticated using (true);
create policy "authenticated write groups_locations" on public.groups_locations for all to authenticated using (true) with check (true);
create policy "authenticated read locations" on public.locations for select to authenticated using (true);
create policy "authenticated write locations" on public.locations for all to authenticated using (true) with check (true);
create policy "authenticated read members" on public.members for select to authenticated using (true);
create policy "authenticated write members" on public.members for all to authenticated using (true) with check (true);
create policy "authenticated read members_groups" on public.members_groups for select to authenticated using (true);
create policy "authenticated write members_groups" on public.members_groups for all to authenticated using (true) with check (true);
create policy "authenticated read members_parents" on public.members_parents for select to authenticated using (true);
create policy "authenticated write members_parents" on public.members_parents for all to authenticated using (true) with check (true);
create policy "authenticated read notifications" on public.notifications for select to authenticated using (true);
create policy "authenticated write notifications" on public.notifications for all to authenticated using (true) with check (true);
create policy "authenticated read parents" on public.parents for select to authenticated using (true);
create policy "authenticated write parents" on public.parents for all to authenticated using (true) with check (true);
create policy "authenticated read payments" on public.payments for select to authenticated using (true);
create policy "authenticated write payments" on public.payments for all to authenticated using (true) with check (true);
create policy "authenticated read profiles" on public.profiles for select to authenticated using (true);
create policy "authenticated write profiles" on public.profiles for all to authenticated using (true) with check (true);
create policy "authenticated read programs" on public.programs for select to authenticated using (true);
create policy "authenticated write programs" on public.programs for all to authenticated using (true) with check (true);
create policy "authenticated read schedule" on public.schedule for select to authenticated using (true);
create policy "authenticated write schedule" on public.schedule for all to authenticated using (true) with check (true);
create policy "authenticated read schedule_acceptance" on public.schedule_acceptance for select to authenticated using (true);
create policy "authenticated write schedule_acceptance" on public.schedule_acceptance for all to authenticated using (true) with check (true);

grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
grant all on all functions in schema public to anon, authenticated, service_role;

commit;
